{*******************************************************}
{* 
{* uTTelefone.pas
{* Delphi Implementation of the Class TTelefone
{* Generated by Enterprise Architect
{* Created on:      16-dez-2014 14:29:49
{* Original author: PROGRAMACAO
{*  
{*******************************************************}

unit Modelo.Entidade.Telefone.TTelefone;

interface

type

  TTelefone = class
  private
    FCodigo         : Integer;
    FClienteCodigo  : Integer;
    FTelefone       : String;
    FTipo           : String;
    procedure SetClienteCodigo(const Value: Integer);
    procedure SetCodigo(const Value: Integer);
    procedure SetTelefone(const Value: String);
    procedure SetTipo(const Value: String);

  public
    constructor Create; overload;
    destructor Destroy; override;
    property Codigo         : Integer read FCodigo write SetCodigo;
    property ClienteCodigo  : Integer read FClienteCodigo write SetClienteCodigo;
    property Telefone       : String read FTelefone write SetTelefone;
    property Tipo           : String read FTipo write SetTipo;

  end;

implementation

{implementation of TTelefone}

constructor TTelefone.Create;
begin
  inherited Create;
end;

destructor TTelefone.Destroy;
begin
  inherited Destroy;
end;

procedure TTelefone.SetClienteCodigo(const Value: Integer);
begin
  FClienteCodigo := Value;
end;

procedure TTelefone.SetCodigo(const Value: Integer);
begin
  FCodigo := Value;
end;

procedure TTelefone.SetTelefone(const Value: String);
begin
  FTelefone := Value;
end;

procedure TTelefone.SetTipo(const Value: String);
begin
  FTipo := Value;
end;

end.