{*******************************************************}
{* 
{* uTNotaFiscalEletronica.pas
{* Delphi Implementation of the Class TNotaFiscalEletronica
{* Generated by Enterprise Architect
{* Created on:      16-dez-2014 14:28:53
{* Original author: PROGRAMACAO
{*  
{*******************************************************}

unit Modelo.Entidade.NFE.TNotaFiscalEletronica;

interface

type

  TNotaFiscalEletronica = class
  private
    FCodigo           : Integer;
    FNotaFiscalCodigo : Integer;
    FChaveAcesso      : String;
    FProtocolo        : String;
    FDataRecebimento  : TDateTime;

    procedure SetChaveAcesso(const Value: String);
    procedure SetCodigo(const Value: Integer);
    procedure SetDataRecebimento(const Value: TDateTime);
    procedure SetNotaFiscalCodigo(const Value: Integer);
    procedure SetProtocolo(const Value: String);

  public

    constructor Create; overload;
    destructor Destroy; override;
    property Codigo           : Integer read FCodigo write SetCodigo;
    property NotaFiscalCodigo : Integer read FNotaFiscalCodigo write SetNotaFiscalCodigo;
    property ChaveAcesso      : String read FChaveAcesso write SetChaveAcesso;
    property Protocolo        : String read FProtocolo write SetProtocolo;
    property DataRecebimento  : TDateTime read FDataRecebimento write SetDataRecebimento;
  end;

implementation

{implementation of TNotaFiscalEletronica}

constructor TNotaFiscalEletronica.Create;
begin
  inherited Create;
end;

destructor TNotaFiscalEletronica.Destroy;
begin
  inherited Destroy;
end;

procedure TNotaFiscalEletronica.SetChaveAcesso(const Value: String);
begin
  FChaveAcesso := Value;
end;

procedure TNotaFiscalEletronica.SetCodigo(const Value: Integer);
begin
  FCodigo := Value;
end;

procedure TNotaFiscalEletronica.SetDataRecebimento(const Value: TDateTime);
begin
  FDataRecebimento := Value;
end;

procedure TNotaFiscalEletronica.SetNotaFiscalCodigo(const Value: Integer);
begin
  FNotaFiscalCodigo := Value;
end;

procedure TNotaFiscalEletronica.SetProtocolo(const Value: String);
begin
  FProtocolo := Value;
end;

end.